-- ============================================
-- JewelShot — Seed Data
-- Run this in Supabase SQL Editor
-- ============================================

-- Clear existing prompts
delete from public.prompts;

-- Stil 1: Yatık poz — yüzük yere yatırılmış, önden ve hafif üstten çekim
-- Note: {{ENGRAVING}} placeholder is replaced by server action with user's custom text
insert into public.prompts (name, description, template, reference_image_url, category, sort_order) values
  (
    'Stil 1',
    'Yüzük yere yatırılmış, önden çekim',
    'Professional high-end e-commerce product photograph of a ring. MANDATORY POSE: The ring MUST be lying flat on its side horizontally on the surface, with the shank (band) facing upward. The ring is NOT standing upright — it is laid down, resting on its side. The shank curves upward like an arch viewed from the front. The camera is positioned at the front of the ring at nearly the same level, facing the decorative front face directly. There is only a very slight upward camera elevation — just enough to peek through the band opening and reveal the inside of the shank. The front face with all stones and design details faces the camera head-on. DO NOT stand the ring upright. DO NOT show the ring vertical. The ring is horizontal, flat, laying on the surface. {{ENGRAVING}}

Preserve every original design detail exactly: stone count, stone arrangement, prong placement, metal color variations including gold, rose gold, white gold, and any two-tone or multi-tone finishes must remain identical to the original. Geometric patterns, filigree work, and all structural elements must be perfectly preserved without any modification. Do not reproduce, show, or include any original text, stamps, hallmarks, or engravings that exist on the original product. CRITICAL: The proportional size ratio between the head (setting/stone area) and the band (shank) MUST remain exactly as in the original. DO NOT make the head larger or smaller relative to the band. DO NOT make the band thicker or thinner relative to the head. The overall scale relationship between all parts of the ring must be identical to the original product. The band cross-section profile and thickness MUST be preserved exactly as in the original — the band must not appear thinner, thicker, flatter, or rounder than the original regardless of viewing angle.

High-end jewelry retouching: ALL metal surfaces on the entire ring must be absolutely flawless, perfectly smooth, and mirror-polished — this includes the band exterior, band interior, AND every metal surface in the head and setting area: prongs, bezels, pavé channels, gallery walls, bridge work, cathedral shoulders, halo frames, and all metal surfaces between and around stones. Every metal area must have the exact same flawless, smooth, polished quality as the band exterior — no area should appear rougher, more textured, or less polished than any other. No visible pitting, porosity, casting marks, grain texture, orange peel texture, or any surface roughness whatsoever anywhere on the ring. No scratches, no dust particles, no fingerprints, no surface imperfections of any kind. Reflections on the metal must be soft, smooth, and gently diffused — NOT sharp or high-contrast. Close-range reflections must blend smoothly into the surface without creating the illusion of bumps, dents, or texture. Avoid harsh specular highlights that mimic surface imperfections. The environment reflected on the metal surfaces must also appear perfectly smooth and clean — no rough, textured, stone-like, or granular surfaces should be visible in any reflection. All reflections must show only a smooth, clean, featureless studio environment. The metal must look like it has been professionally polished and retouched to an immaculate, flawless finish. Preserve intentional micro-textures ONLY if they exist in the original design, such as satin finishes, hammered textures, brushed metal details, or matte sections — but even these must appear clean and deliberate, not rough or accidental.

If the ring contains stones or gems: each stone must look like a real, high-quality precious or semi-precious stone photographed with a macro lens in a professional studio. Each individual facet must be razor-sharp, geometrically precise, and distinctly visible. Stones must exhibit natural brilliance with bright internal light return, visible depth and transparency. The facet junctions must be crisp clean lines, not soft or blurred. Stones must have the unmistakable wet, glassy, alive quality of real cut stones — never dull, flat, frosted, or matte. CRITICAL: Preserve the exact original stone color, material, type, cut, shape, facet pattern, appearance, count, size, and setting without any alteration. If the original stone is a diamond, it MUST remain a diamond. If it is a colored gemstone (sapphire, ruby, emerald, etc.), it MUST remain that exact color and type. If the original stone is round brilliant, it MUST remain round brilliant. If princess cut, emerald cut, marquise, oval, pear, cushion, or any other cut — it MUST stay exactly the same. DO NOT change, replace, or alter the stone cut, shape, color, or material in any way. If the ring has NO stones, DO NOT add any stones — keep the ring plain as in the original.

Lighting: professional dual-source soft studio lighting with carefully controlled specular highlights that reveal three-dimensional form and surface quality. Subtle rim light separating the subject from the background. No lens flare, no glare, no artificial sparkle or glitter effects, no light leaks, no bokeh.

Full depth of field with every element in tack-sharp focus from front to back. No chromatic aberration, no color cast, no vignetting, no barrel distortion.

Background: clean pure white studio backdrop. Very subtle, natural contact shadow where the ring meets the surface, soft and diffused. No reflective floor, no mirrored surface, no gradient, no colored tint.

Shot with a Canon EOS R5 and Canon RF 100mm f/2.8L Macro IS USM lens. RAW file processed in Capture One with professional color grading for luxury e-commerce. The image must be absolutely indistinguishable from a real studio photograph — real optical properties, real light physics, real material behavior. Metal must reflect the studio environment naturally with subtle warm and cool tones in the reflections. Surfaces must show real-world material properties: the natural weight and presence of actual precious metal, not a digitally generated surface. No perfectly uniform gradients on metal — real polished gold and platinum have organic, flowing reflections with subtle variation. No synthetic or plastic-like appearance anywhere. No CGI look, no 3D render aesthetic, no digital illustration style, no video game graphics. No oversaturated colors, no HDR artifacts, no color banding, no posterization. No watermark, no text overlay, no logo, no border, no frame. No extra elements added, no stones removed, no design alterations of any kind.',
    null,
    'yüzük',
    1
  );

-- Stil 2: Dik poz — yüzük dik duruyor, doğrudan önden çekim
insert into public.prompts (name, description, template, reference_image_url, category, sort_order) values
  (
    'Stil 2',
    'Yüzük dik duruyor, doğrudan önden çekim',
    'Professional high-end e-commerce product photograph of a ring. MANDATORY POSE: The ring MUST be standing fully upright, vertically, on the bottom of its band (shank). The shank is at the bottom, touching the surface, supporting the ring like a base. The ring is NOT lying flat, NOT on its side, NOT horizontal. It stands tall and vertical like the letter O resting on a table. The camera is positioned directly in front of the ring at eye level — straight on, facing the decorative front face head-on. The camera angle is nearly horizontal with only a very subtle downward tilt. The front setting with all stones and design details is the absolute primary focus, perfectly centered and symmetrical in the frame. The band curves away naturally toward the back, showing depth and three-dimensionality. DO NOT lay the ring on its side. DO NOT show the ring flat or horizontal. The ring is vertical, upright, standing on its band. {{ENGRAVING}}

Preserve every original design detail exactly: stone count, stone arrangement, prong placement, metal color variations including gold, rose gold, white gold, and any two-tone or multi-tone finishes must remain identical to the original. Geometric patterns, filigree work, and all structural elements must be perfectly preserved without any modification. Do not reproduce, show, or include any original text, stamps, hallmarks, or engravings that exist on the original product. CRITICAL: The proportional size ratio between the head (setting/stone area) and the band (shank) MUST remain exactly as in the original. DO NOT make the head larger or smaller relative to the band. DO NOT make the band thicker or thinner relative to the head. The overall scale relationship between all parts of the ring must be identical to the original product. The band cross-section profile and thickness MUST be preserved exactly as in the original — the band must not appear thinner, thicker, flatter, or rounder than the original regardless of viewing angle.

High-end jewelry retouching: ALL metal surfaces on the entire ring must be absolutely flawless, perfectly smooth, and mirror-polished — this includes the band exterior, band interior, AND every metal surface in the head and setting area: prongs, bezels, pavé channels, gallery walls, bridge work, cathedral shoulders, halo frames, and all metal surfaces between and around stones. Every metal area must have the exact same flawless, smooth, polished quality as the band exterior — no area should appear rougher, more textured, or less polished than any other. No visible pitting, porosity, casting marks, grain texture, orange peel texture, or any surface roughness whatsoever anywhere on the ring. No scratches, no dust particles, no fingerprints, no surface imperfections of any kind. Reflections on the metal must be soft, smooth, and gently diffused — NOT sharp or high-contrast. Close-range reflections must blend smoothly into the surface without creating the illusion of bumps, dents, or texture. Avoid harsh specular highlights that mimic surface imperfections. The environment reflected on the metal surfaces must also appear perfectly smooth and clean — no rough, textured, stone-like, or granular surfaces should be visible in any reflection. All reflections must show only a smooth, clean, featureless studio environment. The metal must look like it has been professionally polished and retouched to an immaculate, flawless finish. Preserve intentional micro-textures ONLY if they exist in the original design, such as satin finishes, hammered textures, brushed metal details, or matte sections — but even these must appear clean and deliberate, not rough or accidental.

If the ring contains stones or gems: each stone must look like a real, high-quality precious or semi-precious stone photographed with a macro lens in a professional studio. Each individual facet must be razor-sharp, geometrically precise, and distinctly visible. Stones must exhibit natural brilliance with bright internal light return, visible depth and transparency. The facet junctions must be crisp clean lines, not soft or blurred. Stones must have the unmistakable wet, glassy, alive quality of real cut stones — never dull, flat, frosted, or matte. CRITICAL: Preserve the exact original stone color, material, type, cut, shape, facet pattern, appearance, count, size, and setting without any alteration. If the original stone is a diamond, it MUST remain a diamond. If it is a colored gemstone (sapphire, ruby, emerald, etc.), it MUST remain that exact color and type. If the original stone is round brilliant, it MUST remain round brilliant. If princess cut, emerald cut, marquise, oval, pear, cushion, or any other cut — it MUST stay exactly the same. DO NOT change, replace, or alter the stone cut, shape, color, or material in any way. If the ring has NO stones, DO NOT add any stones — keep the ring plain as in the original.

Lighting: professional dual-source soft studio lighting with carefully controlled specular highlights that reveal three-dimensional form and surface quality. Subtle rim light separating the subject from the background. No lens flare, no glare, no artificial sparkle or glitter effects, no light leaks, no bokeh.

Full depth of field with every element in tack-sharp focus from front to back. No chromatic aberration, no color cast, no vignetting, no barrel distortion.

Background: clean pure white studio backdrop. Very subtle, natural contact shadow where the ring meets the surface, soft and diffused. No reflective floor, no mirrored surface, no gradient, no colored tint.

Shot with a Canon EOS R5 and Canon RF 100mm f/2.8L Macro IS USM lens. RAW file processed in Capture One with professional color grading for luxury e-commerce. The image must be absolutely indistinguishable from a real studio photograph — real optical properties, real light physics, real material behavior. Metal must reflect the studio environment naturally with subtle warm and cool tones in the reflections. Surfaces must show real-world material properties: the natural weight and presence of actual precious metal, not a digitally generated surface. No perfectly uniform gradients on metal — real polished gold and platinum have organic, flowing reflections with subtle variation. No synthetic or plastic-like appearance anywhere. No CGI look, no 3D render aesthetic, no digital illustration style, no video game graphics. No oversaturated colors, no HDR artifacts, no color banding, no posterization. No watermark, no text overlay, no logo, no border, no frame. No extra elements added, no stones removed, no design alterations of any kind.',
    null,
    'yüzük',
    2
  );

-- Stil 3: Dik poz — yüzük dik duruyor, 3/4 açıdan hafif üstten çekim
insert into public.prompts (name, description, template, reference_image_url, category, sort_order) values
  (
    'Stil 3',
    'Yüzük dik duruyor, 3/4 açıdan çekim',
    'Professional high-end e-commerce product photograph of a ring. The ring is standing upright on its band, resting naturally on a surface. The camera is positioned at a three-quarter angle from the front-right, elevated slightly above the ring — approximately 30 to 40 degrees from horizontal — looking down gently toward the ring. This angle reveals the top face and setting of the ring as the primary focus while also showing the elegant curve and profile of the band. The ring must appear stable, grounded, and naturally balanced — not floating, not tilted, not leaning. {{ENGRAVING}}

Preserve every original design detail exactly: stone count, stone arrangement, prong placement, metal color variations including gold, rose gold, white gold, and any two-tone or multi-tone finishes must remain identical to the original. Geometric patterns, filigree work, and all structural elements must be perfectly preserved without any modification. Do not reproduce, show, or include any original text, stamps, hallmarks, or engravings that exist on the original product. CRITICAL: The proportional size ratio between the head (setting/stone area) and the band (shank) MUST remain exactly as in the original. DO NOT make the head larger or smaller relative to the band. DO NOT make the band thicker or thinner relative to the head. The overall scale relationship between all parts of the ring must be identical to the original product. The band cross-section profile and thickness MUST be preserved exactly as in the original — the band must not appear thinner, thicker, flatter, or rounder than the original regardless of viewing angle.

High-end jewelry retouching: ALL metal surfaces on the entire ring must be absolutely flawless, perfectly smooth, and mirror-polished — this includes the band exterior, band interior, AND every metal surface in the head and setting area: prongs, bezels, pavé channels, gallery walls, bridge work, cathedral shoulders, halo frames, and all metal surfaces between and around stones. Every metal area must have the exact same flawless, smooth, polished quality as the band exterior — no area should appear rougher, more textured, or less polished than any other. No visible pitting, porosity, casting marks, grain texture, orange peel texture, or any surface roughness whatsoever anywhere on the ring. No scratches, no dust particles, no fingerprints, no surface imperfections of any kind. Reflections on the metal must be soft, smooth, and gently diffused — NOT sharp or high-contrast. Close-range reflections must blend smoothly into the surface without creating the illusion of bumps, dents, or texture. Avoid harsh specular highlights that mimic surface imperfections. The environment reflected on the metal surfaces must also appear perfectly smooth and clean — no rough, textured, stone-like, or granular surfaces should be visible in any reflection. All reflections must show only a smooth, clean, featureless studio environment. The metal must look like it has been professionally polished and retouched to an immaculate, flawless finish. Preserve intentional micro-textures ONLY if they exist in the original design, such as satin finishes, hammered textures, brushed metal details, or matte sections — but even these must appear clean and deliberate, not rough or accidental.

If the ring contains stones or gems: each stone must look like a real, high-quality precious or semi-precious stone photographed with a macro lens in a professional studio. Each individual facet must be razor-sharp, geometrically precise, and distinctly visible. Stones must exhibit natural brilliance with bright internal light return, visible depth and transparency. The facet junctions must be crisp clean lines, not soft or blurred. Stones must have the unmistakable wet, glassy, alive quality of real cut stones — never dull, flat, frosted, or matte. CRITICAL: Preserve the exact original stone color, material, type, cut, shape, facet pattern, appearance, count, size, and setting without any alteration. If the original stone is a diamond, it MUST remain a diamond. If it is a colored gemstone (sapphire, ruby, emerald, etc.), it MUST remain that exact color and type. If the original stone is round brilliant, it MUST remain round brilliant. If princess cut, emerald cut, marquise, oval, pear, cushion, or any other cut — it MUST stay exactly the same. DO NOT change, replace, or alter the stone cut, shape, color, or material in any way. If the ring has NO stones, DO NOT add any stones — keep the ring plain as in the original.

Lighting: professional dual-source soft studio lighting with carefully controlled specular highlights that reveal three-dimensional form and surface quality. Subtle rim light separating the subject from the background. No lens flare, no glare, no artificial sparkle or glitter effects, no light leaks, no bokeh.

Full depth of field with every element in tack-sharp focus from front to back. No chromatic aberration, no color cast, no vignetting, no barrel distortion.

Background: clean pure white studio backdrop. Very subtle, natural contact shadow where the ring meets the surface, soft and diffused. No reflective floor, no mirrored surface, no gradient, no colored tint.

Shot with a Canon EOS R5 and Canon RF 100mm f/2.8L Macro IS USM lens. RAW file processed in Capture One with professional color grading for luxury e-commerce. The image must be absolutely indistinguishable from a real studio photograph — real optical properties, real light physics, real material behavior. Metal must reflect the studio environment naturally with subtle warm and cool tones in the reflections. Surfaces must show real-world material properties: the natural weight and presence of actual precious metal, not a digitally generated surface. No perfectly uniform gradients on metal — real polished gold and platinum have organic, flowing reflections with subtle variation. No synthetic or plastic-like appearance anywhere. No CGI look, no 3D render aesthetic, no digital illustration style, no video game graphics. No oversaturated colors, no HDR artifacts, no color banding, no posterization. No watermark, no text overlay, no logo, no border, no frame. No extra elements added, no stones removed, no design alterations of any kind.',
    null,
    'yüzük',
    3
  );

-- Stil 4: Dik poz — yüzük dik duruyor, sol ön 3/4 açıdan profil çekim
insert into public.prompts (name, description, template, reference_image_url, category, sort_order) values
  (
    'Stil 4',
    'Yüzük dik duruyor, sol ön 3/4 açıdan profil çekim',
    'Professional high-end e-commerce product photograph of a ring. MANDATORY POSE: The ring MUST be standing fully upright, vertically, on the bottom of its band (shank). The shank is at the bottom, touching the surface. The ring is NOT lying flat, NOT on its side, NOT horizontal. The camera is positioned at a three-quarter angle from the front-left of the ring, elevated slightly above — approximately 20 to 30 degrees from horizontal. This angle shows the decorative head and setting on the left side of the frame, while the band sweeps and curves elegantly toward the right and slightly away from the camera. The profile and side silhouette of the setting is prominently visible, revealing the height and dimensionality of the head from the side. The band tapers gracefully as it extends away. The ring must appear stable, grounded, and naturally balanced. DO NOT lay the ring on its side. DO NOT show the ring flat or horizontal. DO NOT shoot from directly in front — the camera is offset to the left, capturing the three-quarter profile. {{ENGRAVING}}

Preserve every original design detail exactly: stone count, stone arrangement, prong placement, metal color variations including gold, rose gold, white gold, and any two-tone or multi-tone finishes must remain identical to the original. Geometric patterns, filigree work, and all structural elements must be perfectly preserved without any modification. Do not reproduce, show, or include any original text, stamps, hallmarks, or engravings that exist on the original product. CRITICAL: The proportional size ratio between the head (setting/stone area) and the band (shank) MUST remain exactly as in the original. DO NOT make the head larger or smaller relative to the band. DO NOT make the band thicker or thinner relative to the head. The overall scale relationship between all parts of the ring must be identical to the original product. The band cross-section profile and thickness MUST be preserved exactly as in the original — the band must not appear thinner, thicker, flatter, or rounder than the original regardless of viewing angle.

High-end jewelry retouching: ALL metal surfaces on the entire ring must be absolutely flawless, perfectly smooth, and mirror-polished — this includes the band exterior, band interior, AND every metal surface in the head and setting area: prongs, bezels, pavé channels, gallery walls, bridge work, cathedral shoulders, halo frames, and all metal surfaces between and around stones. Every metal area must have the exact same flawless, smooth, polished quality as the band exterior — no area should appear rougher, more textured, or less polished than any other. No visible pitting, porosity, casting marks, grain texture, orange peel texture, or any surface roughness whatsoever anywhere on the ring. No scratches, no dust particles, no fingerprints, no surface imperfections of any kind. Reflections on the metal must be soft, smooth, and gently diffused — NOT sharp or high-contrast. Close-range reflections must blend smoothly into the surface without creating the illusion of bumps, dents, or texture. Avoid harsh specular highlights that mimic surface imperfections. The environment reflected on the metal surfaces must also appear perfectly smooth and clean — no rough, textured, stone-like, or granular surfaces should be visible in any reflection. All reflections must show only a smooth, clean, featureless studio environment. The metal must look like it has been professionally polished and retouched to an immaculate, flawless finish. Preserve intentional micro-textures ONLY if they exist in the original design, such as satin finishes, hammered textures, brushed metal details, or matte sections — but even these must appear clean and deliberate, not rough or accidental.

If the ring contains stones or gems: each stone must look like a real, high-quality precious or semi-precious stone photographed with a macro lens in a professional studio. Each individual facet must be razor-sharp, geometrically precise, and distinctly visible. Stones must exhibit natural brilliance with bright internal light return, visible depth and transparency. The facet junctions must be crisp clean lines, not soft or blurred. Stones must have the unmistakable wet, glassy, alive quality of real cut stones — never dull, flat, frosted, or matte. CRITICAL: Preserve the exact original stone color, material, type, cut, shape, facet pattern, appearance, count, size, and setting without any alteration. If the original stone is a diamond, it MUST remain a diamond. If it is a colored gemstone (sapphire, ruby, emerald, etc.), it MUST remain that exact color and type. If the original stone is round brilliant, it MUST remain round brilliant. If princess cut, emerald cut, marquise, oval, pear, cushion, or any other cut — it MUST stay exactly the same. DO NOT change, replace, or alter the stone cut, shape, color, or material in any way. If the ring has NO stones, DO NOT add any stones — keep the ring plain as in the original.

Lighting: professional dual-source soft studio lighting with carefully controlled specular highlights that reveal three-dimensional form and surface quality. Subtle rim light separating the subject from the background. No lens flare, no glare, no artificial sparkle or glitter effects, no light leaks, no bokeh.

Full depth of field with every element in tack-sharp focus from front to back. No chromatic aberration, no color cast, no vignetting, no barrel distortion.

Background: clean pure white studio backdrop. Very subtle, natural contact shadow where the ring meets the surface, soft and diffused. No reflective floor, no mirrored surface, no gradient, no colored tint.

Shot with a Canon EOS R5 and Canon RF 100mm f/2.8L Macro IS USM lens. RAW file processed in Capture One with professional color grading for luxury e-commerce. The image must be absolutely indistinguishable from a real studio photograph — real optical properties, real light physics, real material behavior. Metal must reflect the studio environment naturally with subtle warm and cool tones in the reflections. Surfaces must show real-world material properties: the natural weight and presence of actual precious metal, not a digitally generated surface. No perfectly uniform gradients on metal — real polished gold and platinum have organic, flowing reflections with subtle variation. No synthetic or plastic-like appearance anywhere. No CGI look, no 3D render aesthetic, no digital illustration style, no video game graphics. No oversaturated colors, no HDR artifacts, no color banding, no posterization. No watermark, no text overlay, no logo, no border, no frame. No extra elements added, no stones removed, no design alterations of any kind.',
    null,
    'yüzük',
    4
  );

-- Stil 5: Dik poz — yüzük dik duruyor, tam yandan çekim, band seviyesinde
insert into public.prompts (name, description, template, reference_image_url, category, sort_order) values
  (
    'Stil 5',
    'Yüzük dik duruyor, tam yandan band seviyesinde çekim',
    'Professional high-end e-commerce product photograph of a ring. MANDATORY POSE: The ring MUST be standing fully upright, vertically, on the bottom of its band (shank). The shank is at the bottom, touching the surface. The ring is NOT lying flat, NOT on its side, NOT horizontal. The camera is positioned at the exact SIDE of the ring, at the same height as the band — perfectly level with the center of the ring opening. This is a pure side profile view. The full circular shape of the band is visible as a complete circle silhouette. The setting and head sit at the very top of the circle. The viewer looks through the ring opening from the side, seeing the hollow interior of the band circle. The camera does NOT look at the front or back of the ring — it looks at the side edge. DO NOT shoot from the front. DO NOT shoot from the back. DO NOT shoot from above. The camera is at band level, looking at the ring from the side, perpendicular to the front face. DO NOT lay the ring on its side. DO NOT show the ring flat or horizontal. {{ENGRAVING}}

Preserve every original design detail exactly: stone count, stone arrangement, prong placement, metal color variations including gold, rose gold, white gold, and any two-tone or multi-tone finishes must remain identical to the original. Geometric patterns, filigree work, and all structural elements must be perfectly preserved without any modification. Do not reproduce, show, or include any original text, stamps, hallmarks, or engravings that exist on the original product. CRITICAL: The proportional size ratio between the head (setting/stone area) and the band (shank) MUST remain exactly as in the original. DO NOT make the head larger or smaller relative to the band. DO NOT make the band thicker or thinner relative to the head. The overall scale relationship between all parts of the ring must be identical to the original product. The band cross-section profile and thickness MUST be preserved exactly as in the original — the band must not appear thinner, thicker, flatter, or rounder than the original regardless of viewing angle.

High-end jewelry retouching: ALL metal surfaces on the entire ring must be absolutely flawless, perfectly smooth, and mirror-polished — this includes the band exterior, band interior, AND every metal surface in the head and setting area: prongs, bezels, pavé channels, gallery walls, bridge work, cathedral shoulders, halo frames, and all metal surfaces between and around stones. Every metal area must have the exact same flawless, smooth, polished quality as the band exterior — no area should appear rougher, more textured, or less polished than any other. No visible pitting, porosity, casting marks, grain texture, orange peel texture, or any surface roughness whatsoever anywhere on the ring. No scratches, no dust particles, no fingerprints, no surface imperfections of any kind. Reflections on the metal must be soft, smooth, and gently diffused — NOT sharp or high-contrast. Close-range reflections must blend smoothly into the surface without creating the illusion of bumps, dents, or texture. Avoid harsh specular highlights that mimic surface imperfections. The environment reflected on the metal surfaces must also appear perfectly smooth and clean — no rough, textured, stone-like, or granular surfaces should be visible in any reflection. All reflections must show only a smooth, clean, featureless studio environment. The metal must look like it has been professionally polished and retouched to an immaculate, flawless finish. Preserve intentional micro-textures ONLY if they exist in the original design, such as satin finishes, hammered textures, brushed metal details, or matte sections — but even these must appear clean and deliberate, not rough or accidental.

If the ring contains stones or gems: each stone must look like a real, high-quality precious or semi-precious stone photographed with a macro lens in a professional studio. Each individual facet must be razor-sharp, geometrically precise, and distinctly visible. Stones must exhibit natural brilliance with bright internal light return, visible depth and transparency. The facet junctions must be crisp clean lines, not soft or blurred. Stones must have the unmistakable wet, glassy, alive quality of real cut stones — never dull, flat, frosted, or matte. CRITICAL: Preserve the exact original stone color, material, type, cut, shape, facet pattern, appearance, count, size, and setting without any alteration. If the original stone is a diamond, it MUST remain a diamond. If it is a colored gemstone (sapphire, ruby, emerald, etc.), it MUST remain that exact color and type. If the original stone is round brilliant, it MUST remain round brilliant. If princess cut, emerald cut, marquise, oval, pear, cushion, or any other cut — it MUST stay exactly the same. DO NOT change, replace, or alter the stone cut, shape, color, or material in any way. If the ring has NO stones, DO NOT add any stones — keep the ring plain as in the original.

Lighting: professional dual-source soft studio lighting with carefully controlled specular highlights that reveal three-dimensional form and surface quality. Subtle rim light separating the subject from the background. No lens flare, no glare, no artificial sparkle or glitter effects, no light leaks, no bokeh.

Full depth of field with every element in tack-sharp focus from front to back. No chromatic aberration, no color cast, no vignetting, no barrel distortion.

Background: clean pure white studio backdrop. Very subtle, natural contact shadow where the ring meets the surface, soft and diffused. No reflective floor, no mirrored surface, no gradient, no colored tint.

Shot with a Canon EOS R5 and Canon RF 100mm f/2.8L Macro IS USM lens. RAW file processed in Capture One with professional color grading for luxury e-commerce. The image must be absolutely indistinguishable from a real studio photograph — real optical properties, real light physics, real material behavior. Metal must reflect the studio environment naturally with subtle warm and cool tones in the reflections. Surfaces must show real-world material properties: the natural weight and presence of actual precious metal, not a digitally generated surface. No perfectly uniform gradients on metal — real polished gold and platinum have organic, flowing reflections with subtle variation. No synthetic or plastic-like appearance anywhere. No CGI look, no 3D render aesthetic, no digital illustration style, no video game graphics. No oversaturated colors, no HDR artifacts, no color banding, no posterization. No watermark, no text overlay, no logo, no border, no frame. No extra elements added, no stones removed, no design alterations of any kind.',
    null,
    'yüzük',
    5
  );

-- Stil 6: Dik poz — yüzük dik duruyor, band seviyesinden neredeyse yandan, hafif sola dönük
insert into public.prompts (name, description, template, reference_image_url, category, sort_order) values
  (
    'Stil 6',
    'Yüzük dik duruyor, band seviyesinden hafif sola dönük yan çekim',
    'Professional high-end e-commerce product photograph of a ring. MANDATORY POSE: The ring MUST be standing fully upright, vertically, on the bottom of its band (shank). The shank is at the bottom, touching the surface. The ring is NOT lying flat, NOT on its side, NOT horizontal. The camera is positioned at BAND LEVEL — at the same height as the center of the ring opening. This is almost a pure side view, but the ring is very slightly turned to the left — rotated only about 15 to 20 degrees from a pure side profile. Because of this subtle rotation, the band is seen mostly as a circle but with a slight hint of the band edge thickness visible. The near side of the band is slightly closer to the camera than the far side. The setting at the top is seen mostly from the side but angled very slightly to reveal a hint of the front face. This is NOT a diagonal or three-quarter view — it is fundamentally a side view with a very subtle, barely perceptible rotation. DO NOT rotate the ring more than 20 degrees. DO NOT show a full front view. DO NOT show a full diagonal view. The camera stays at band level, almost directly to the side. DO NOT shoot from above. DO NOT lay the ring on its side. DO NOT show the ring flat or horizontal. {{ENGRAVING}}

Preserve every original design detail exactly: stone count, stone arrangement, prong placement, metal color variations including gold, rose gold, white gold, and any two-tone or multi-tone finishes must remain identical to the original. Geometric patterns, filigree work, and all structural elements must be perfectly preserved without any modification. Do not reproduce, show, or include any original text, stamps, hallmarks, or engravings that exist on the original product. CRITICAL: The proportional size ratio between the head (setting/stone area) and the band (shank) MUST remain exactly as in the original. DO NOT make the head larger or smaller relative to the band. DO NOT make the band thicker or thinner relative to the head. The overall scale relationship between all parts of the ring must be identical to the original product. The band cross-section profile and thickness MUST be preserved exactly as in the original — the band must not appear thinner, thicker, flatter, or rounder than the original regardless of viewing angle.

High-end jewelry retouching: ALL metal surfaces on the entire ring must be absolutely flawless, perfectly smooth, and mirror-polished — this includes the band exterior, band interior, AND every metal surface in the head and setting area: prongs, bezels, pavé channels, gallery walls, bridge work, cathedral shoulders, halo frames, and all metal surfaces between and around stones. Every metal area must have the exact same flawless, smooth, polished quality as the band exterior — no area should appear rougher, more textured, or less polished than any other. No visible pitting, porosity, casting marks, grain texture, orange peel texture, or any surface roughness whatsoever anywhere on the ring. No scratches, no dust particles, no fingerprints, no surface imperfections of any kind. Reflections on the metal must be soft, smooth, and gently diffused — NOT sharp or high-contrast. Close-range reflections must blend smoothly into the surface without creating the illusion of bumps, dents, or texture. Avoid harsh specular highlights that mimic surface imperfections. The environment reflected on the metal surfaces must also appear perfectly smooth and clean — no rough, textured, stone-like, or granular surfaces should be visible in any reflection. All reflections must show only a smooth, clean, featureless studio environment. The metal must look like it has been professionally polished and retouched to an immaculate, flawless finish. Preserve intentional micro-textures ONLY if they exist in the original design, such as satin finishes, hammered textures, brushed metal details, or matte sections — but even these must appear clean and deliberate, not rough or accidental.

If the ring contains stones or gems: each stone must look like a real, high-quality precious or semi-precious stone photographed with a macro lens in a professional studio. Each individual facet must be razor-sharp, geometrically precise, and distinctly visible. Stones must exhibit natural brilliance with bright internal light return, visible depth and transparency. The facet junctions must be crisp clean lines, not soft or blurred. Stones must have the unmistakable wet, glassy, alive quality of real cut stones — never dull, flat, frosted, or matte. CRITICAL: Preserve the exact original stone color, material, type, cut, shape, facet pattern, appearance, count, size, and setting without any alteration. If the original stone is a diamond, it MUST remain a diamond. If it is a colored gemstone (sapphire, ruby, emerald, etc.), it MUST remain that exact color and type. If the original stone is round brilliant, it MUST remain round brilliant. If princess cut, emerald cut, marquise, oval, pear, cushion, or any other cut — it MUST stay exactly the same. DO NOT change, replace, or alter the stone cut, shape, color, or material in any way. If the ring has NO stones, DO NOT add any stones — keep the ring plain as in the original.

Lighting: professional dual-source soft studio lighting with carefully controlled specular highlights that reveal three-dimensional form and surface quality. Subtle rim light separating the subject from the background. No lens flare, no glare, no artificial sparkle or glitter effects, no light leaks, no bokeh.

Full depth of field with every element in tack-sharp focus from front to back. No chromatic aberration, no color cast, no vignetting, no barrel distortion.

Background: clean pure white studio backdrop. Very subtle, natural contact shadow where the ring meets the surface, soft and diffused. No reflective floor, no mirrored surface, no gradient, no colored tint.

Shot with a Canon EOS R5 and Canon RF 100mm f/2.8L Macro IS USM lens. RAW file processed in Capture One with professional color grading for luxury e-commerce. The image must be absolutely indistinguishable from a real studio photograph — real optical properties, real light physics, real material behavior. Metal must reflect the studio environment naturally with subtle warm and cool tones in the reflections. Surfaces must show real-world material properties: the natural weight and presence of actual precious metal, not a digitally generated surface. No perfectly uniform gradients on metal — real polished gold and platinum have organic, flowing reflections with subtle variation. No synthetic or plastic-like appearance anywhere. No CGI look, no 3D render aesthetic, no digital illustration style, no video game graphics. No oversaturated colors, no HDR artifacts, no color banding, no posterization. No watermark, no text overlay, no logo, no border, no frame. No extra elements added, no stones removed, no design alterations of any kind.',
    null,
    'yüzük',
    6
  );

-- Give credits (run after first signup)
-- update public.profiles set credits = 20 where id = (select id from public.profiles limit 1);

-- ============================================
-- Kolye (Necklace) Prompts
-- ============================================

-- Kolye Stil 1: Genel görünüm — eliptik kılavuz çizgisine oturtulmuş (TEST)
insert into public.prompts (name, description, template, reference_image_url, category, sort_order) values
  (
    'Stil 1',
    'Kolye düz, eliptik kılavuz çizgisine oturtulmuş',
    'Professional high-end e-commerce product photograph of a necklace. The input consists of multiple reference images:
- Image 1 (pose_reference): A reference image showing a necklace floating in a perfect elliptical/oval shape on a clean white background. This defines the EXACT geometric layout, pose, and spatial arrangement the final necklace must follow.
- Image 2 (necklace_general_image): The complete overall view of the necklace — use this as the primary product reference for the entire piece.
- Image 3 (necklace_pendant_image): Close-up detail of the pendant, charm, or centerpiece.
- Image 4 (necklace_chain_detail_image): Close-up of the chain links and texture.
- Image 5 (necklace_clasp_image): The clasp/closure mechanism.

CORE GEOMETRY & POSE: The final necklace MUST be shaped and positioned exactly like the necklace in Image 1. It must form a perfect, continuous elliptical or oval loop floating in the center of the frame on the pure white background. The pendant/centerpiece is at the very bottom center of the loop, facing the camera directly. The chain extends perfectly along the elliptical path upwards on both sides, joining at the clasp at the top center. The camera is positioned looking straight at the floating necklace.

Using ALL reference images, produce a single professional product photograph that accurately represents the complete necklace. 
CRITICAL ENFORCEMENTS:
1. NO SHADOWS (FLOATING): The necklace MUST appear entirely isolated and floating. There must be absolutely NO drop shadows, NO contact shadows, and NO ambient occlusion cast onto the background. The background must remain pure, uninterrupted white everywhere.
2. CHAIN TOPOLOGY: You MUST meticulously study Image 4 (chain detail) and Image 2. Replicate the EXACT type, shape, and thickness of the chain links. If there are alternating link types (e.g. one long oval link followed by three small round links), you MUST count them and perfectly replicate that exact mathematical sequence across the entire necklace. If the links are twisted, flattened, or faceted, replicate that exact structure.
3. CLASP ORIENTATION: You MUST study Image 5 (clasp). The clasp mechanism must be placed at the top center of the necklace. The opening/mouth of the clasp (the part that clicks open) MUST face downwards towards the pendant. 
4. NO TEXT/LETTERS: There must be absolutely NO letters, text, watermarks, or logos anywhere on the necklace, pendant, or background.
5. EXACT REPLICATION: Every detail from every reference image must be faithfully preserved — stone colors, metal finish, chain pattern, clasp design, pendant shape. DO NOT alter, simplify, or reinterpret any design element.

If the necklace contains stones or gems: each stone must look like a real, high-quality precious or semi-precious stone. Preserve the exact original stone color, material, type, cut, shape, and setting. If the necklace has NO stones, DO NOT add any.

High-end jewelry retouching: ALL metal surfaces must be absolutely flawless, perfectly smooth, and mirror-polished. No scratches, no dust, no fingerprints, no stains, no smudges. Reflections must be soft, bright, and gently diffused. CRITICAL: There must be NO black, dark, muddy, or dirty reflections anywhere on the metal. The entire necklace must be uniformly bright, evenly lit, and immaculately clean from end to end. 

Lighting: professional softbox studio lighting providing 100% even illumination across the entire piece. No harsh shadows on the product itself. No lens flare, no glare, no artificial sparkle. Every part of the chain, pendant, and clasp must be equally visible, bright, and exceptionally clear with consistent high-key lighting.

Background: clean pure white studio backdrop (RGB: 255, 255, 255). The product must be floating completely isolated with ZERO shadows cast onto the background. No reflective floor, no gradient, no colored tint.

Shot with a medium format Hasselblad H6D-100c and 120mm macro lens for absolute maximum clarity and microscopic detail. The image must be absolutely indistinguishable from a real world-class studio photograph, perfectly retouched to eliminate any dark environmental reflections or impurities.',
    null,
    'kolye',
    1
  );

-- ============================================
-- Küpe (Earring) Prompts
-- ============================================

-- Küpe Stil 1: Çift Küpe (Önden ve Yandan)
insert into public.prompts (name, description, template, reference_image_url, category, sort_order) values
  (
    'Stil 1',
    'Çift Küpe (Önden ve Yandan Görünüm)',
    'Professional high-end e-commerce product photograph of a matching pair of earrings. The input consists of multiple reference images:
- Image 1 (front_view): The primary front view of the earring.
- Image 2 (side_view, optional): A side-profile view showing the depth, clasp mechanism, and structural thickness of the earring.

CORE GEOMETRY & POSE: The final image MUST contain EXACTLY TWO matching earrings, forming a perfect pair. They must be displayed together on a clean white background. Both earrings must be absolutely identical in design, materials, stones, and proportions, mirroring each other gracefully. The primary earring should be positioned slightly forward or angled to display its front face prominently (referencing Image 1), while the secondary earring should be positioned slightly behind, beside, or angled to show its side profile or depth (referencing Image 2 if provided, or otherwise logically interpreting the depth). The earrings are NOT being worn; they are isolated on a pristine surface or floating cleanly.

CRITICAL ENFORCEMENTS:
1. MATCHING PAIR: You MUST generate exactly TWO earrings. They must be an identical pair. Do not generate a single earring.
2. NO SHADOWS (FLOATING) OR SOFT CONTACT SHADOWS: The background must remain pure, uninterrupted white everywhere (RGB: 255, 255, 255). If resting on a surface, only a very soft, natural, and subtle contact shadow is permitted. No dark, heavy, or distracting shadows.
3. EXACT REPLICATION: Every detail from the reference images must be faithfully preserved — stone colors, metal finish, clasp type (e.g., butterfly back, lever back, huggie), structural geometry. DO NOT alter, simplify, or reinterpret any design element. The side profile (if provided in Image 2) must be integrated to show the true 3D structure and thickness of the metal.
4. NO TEXT/LETTERS: There must be absolutely NO letters, text, watermarks, or logos anywhere on the earrings or background.

If the earrings contain stones or gems: each stone must look like a real, high-quality precious or semi-precious stone. Preserve the exact original stone color, material, type, cut, shape, and setting. If the earrings have NO stones, DO NOT add any. Each individual facet must be razor-sharp, geometrically precise, and distinctly visible.

High-end jewelry retouching: ALL metal surfaces must be absolutely flawless, perfectly smooth, and mirror-polished. No scratches, no dust, no fingerprints, no stains, no smudges. Reflections must be soft, bright, and gently diffused. CRITICAL: There must be NO black, dark, muddy, or dirty reflections anywhere on the metal. The entire pair must be uniformly bright, evenly lit, and immaculately clean.

Lighting: professional softbox studio lighting providing 100% even illumination across both pieces. No harsh shadows on the products themselves. No lens flare, no glare, no artificial sparkle. Every part of the earrings must be equally visible, bright, and exceptionally clear with consistent high-key lighting.

Shot with a medium format Hasselblad H6D-100c and 120mm macro lens for absolute maximum clarity and microscopic detail. The image must be absolutely indistinguishable from a real world-class studio photograph of a pair of earrings.',
    null,
    'küpe',
    1
  );

-- ============================================
-- Bileklik (Bracelet) Prompts
-- ============================================

-- Bileklik Stil 1: Üstten Görünüm
insert into public.prompts (name, description, template, reference_image_url, category, sort_order) values
  (
    'Stil 1',
    'Bileklik (Üstten veya Çapraz Görünüm)',
    'Professional high-end e-commerce product photograph of a luxury bracelet. The input consists of reference images providing the structural layout, metal type, stone placement, and overall design of the bracelet.

CORE GEOMETRY & POSE: The final image MUST showcase the bracelet beautifully laid out or structurally posed on a clean white background. It MUST strictly follow the geometry and chain structure provided in the reference images. Whether it is a rigid bangle, a tennis bracelet, or a fluid chain, its spatial flow from the reference must be preserved. The bracelet is NOT being worn; it is isolated on a pristine surface or floating cleanly.

CRITICAL ENFORCEMENTS:
1. NO SHADOWS (FLOATING) OR SOFT CONTACT SHADOWS: The background must remain pure, uninterrupted white everywhere (RGB: 255, 255, 255). If resting on a surface, only a very soft, natural, and subtle contact shadow is permitted underneath the chain/band. No dark, heavy, distracting, or disconnected shadows.
2. EXACT REPLICATION: Every detail from the reference image must be faithfully preserved — stone colors, metal finish, clasp mechanism, link type, and structural rigidity. DO NOT alter, simplify, or reinterpret any design element.
3. NO TEXT/LETTERS: There must be absolutely NO letters, text, watermarks, or logos anywhere on the bracelet or background.

If the bracelet contains stones or gems: each stone must look like a real, high-quality precious or semi-precious stone. Preserve the exact original stone color, material, type, cut, shape, and setting down the entire line of the bracelet. If the bracelet has NO stones, DO NOT add any. Each individual facet must be razor-sharp, geometrically precise, and distinctly visible.

High-end jewelry retouching: ALL metal surfaces must be absolutely flawless, perfectly smooth, and mirror-polished. No scratches, no dust, no fingerprints, no stains, no smudges. Reflections must be soft, bright, and gently diffused. CRITICAL: There must be NO black, dark, muddy, or dirty reflections anywhere on the metal. The entire band/chain must be uniformly bright, evenly lit, and immaculately clean.

Lighting: professional softbox studio lighting providing 100% even illumination across the entire length of the piece. No harsh shadows on the product itself. No lens flare, no glare, no artificial sparkle. Every link, stone, and the clasp must be equally visible, bright, and exceptionally clear with consistent high-key lighting.

Shot with a medium format Hasselblad H6D-100c and 120mm macro lens for absolute maximum clarity and microscopic detail. The image must be absolutely indistinguishable from a real world-class studio photograph.',
    null,
    'bileklik',
    1
  );
